(file (name "aescm-{version}.tar.gz")
      (title "aescm")
      (note "Embedded Scheme processor; source code")
      (manual-original-url "https://sourceforge.net/projects/escm/files/aescm/{version}/{name}/download")
      (version "0.26"))

(file (name "aescm-{version}.tar.gz")
      (title "aescm")
      (note "Embedded Scheme processor; source code")
      (manual-original-url "https://sourceforge.net/projects/escm/files/aescm/{version}/{name}/download")
      (version "0.30"))

(file (name "aescm-{version}.tar.gz")
      (title "aescm")
      (note "Embedded Scheme processor; source code")
      (manual-original-url "https://sourceforge.net/projects/escm/files/aescm/{version}/{name}/download")
      (version "0.31"))

(file (name "aescm-{version}.tar.gz")
      (title "aescm")
      (note "Embedded Scheme processor; source code")
      (manual-original-url "https://sourceforge.net/projects/escm/files/aescm/{version}/{name}/download")
      (version "0.32"))

(file (name "{scheme-id}-scheme-{scheme-version}.tgz")
      (title "Chibi-Scheme")
      (note "Scheme implementation; source code")
      (original-url "http://synthcode.com/scheme/{scheme-id}/{name}")
      (scheme-id "chibi")
      (scheme-version "0.9.1"))

(file (name "{scheme-id}-{scheme-version}.tar.gz")
      (title "CHICKEN")
      (note "Scheme implementation; source code")
      (original-url "https://code.call-cc.org/releases/{scheme-version}/{name}")
      (scheme-id "chicken")
      (scheme-version "3.0.0"))

(file (name "{scheme-id}-{scheme-version}.tar.gz")
      (title "CHICKEN")
      (note "Scheme implementation; source code")
      (original-url "https://code.call-cc.org/releases/{scheme-version}/{name}")
      (scheme-id "chicken")
      (scheme-version "3.1.0"))

(file (name "{scheme-id}-{scheme-version}.tar.gz")
      (title "CHICKEN")
      (note "Scheme implementation; source code")
      (original-url "https://code.call-cc.org/releases/{scheme-version}/{name}")
      (scheme-id "chicken")
      (scheme-version "3.2.0"))

(file (name "{scheme-id}-{scheme-version}.tar.gz")
      (title "CHICKEN")
      (note "Scheme implementation; source code")
      (original-url "https://code.call-cc.org/releases/{scheme-version}/{name}")
      (scheme-id "chicken")
      (scheme-version "3.3.0"))

(file (name "{scheme-id}-{scheme-version}.tar.gz")
      (title "CHICKEN")
      (note "Scheme implementation; source code")
      (original-url "https://code.call-cc.org/releases/{scheme-version}/{name}")
      (scheme-id "chicken")
      (scheme-version "3.4.0"))

(file (name "{scheme-id}-{scheme-version}.tar.gz")
      (title "CHICKEN")
      (note "Scheme implementation; source code")
      (original-url "https://code.call-cc.org/releases/{scheme-version}/{name}")
      (scheme-id "chicken")
      (scheme-version "4.0.0"))

(file (name "{scheme-id}-{scheme-version}.tar.gz")
      (title "CHICKEN")
      (note "Scheme implementation; source code")
      (original-url "https://code.call-cc.org/releases/{scheme-version}/{name}")
      (scheme-id "chicken")
      (scheme-version "4.1.0"))

(file (name "{scheme-id}-{scheme-version}.tar.gz")
      (title "CHICKEN")
      (note "Scheme implementation; source code")
      (original-url "https://code.call-cc.org/releases/{scheme-version}/{name}")
      (scheme-id "chicken")
      (scheme-version "4.10.0"))

(file (name "{scheme-id}-{scheme-version}.tar.gz")
      (title "CHICKEN")
      (note "Scheme implementation; source code")
      (original-url "https://code.call-cc.org/releases/{scheme-version}/{name}")
      (scheme-id "chicken")
      (scheme-version "4.11.0"))

(file (name "{scheme-id}-{scheme-version}.tar.gz")
      (title "CHICKEN")
      (note "Scheme implementation; source code")
      (original-url "https://code.call-cc.org/releases/{scheme-version}/{name}")
      (scheme-id "chicken")
      (scheme-version "4.12.0"))

(file (name "{scheme-id}-{scheme-version}.tar.gz")
      (title "CHICKEN")
      (note "Scheme implementation; source code")
      (original-url "https://code.call-cc.org/releases/{scheme-version}/{name}")
      (scheme-id "chicken")
      (scheme-version "4.13.0"))

(file (name "{scheme-id}-{scheme-version}.tar.gz")
      (title "CHICKEN")
      (note "Scheme implementation; source code")
      (original-url "https://code.call-cc.org/releases/{scheme-version}/{name}")
      (scheme-id "chicken")
      (scheme-version "4.2.0"))

(file (name "{scheme-id}-{scheme-version}.tar.gz")
      (title "CHICKEN")
      (note "Scheme implementation; source code")
      (original-url "https://code.call-cc.org/releases/{scheme-version}/{name}")
      (scheme-id "chicken")
      (scheme-version "4.3.0"))

(file (name "{scheme-id}-{scheme-version}.tar.gz")
      (title "CHICKEN")
      (note "Scheme implementation; source code")
      (original-url "https://code.call-cc.org/releases/{scheme-version}/{name}")
      (scheme-id "chicken")
      (scheme-version "4.4.0"))

(file (name "{scheme-id}-{scheme-version}.tar.gz")
      (title "CHICKEN")
      (note "Scheme implementation; source code")
      (original-url "https://code.call-cc.org/releases/{scheme-version}/{name}")
      (scheme-id "chicken")
      (scheme-version "4.5.0"))

(file (name "{scheme-id}-{scheme-version}.tar.gz")
      (title "CHICKEN")
      (note "Scheme implementation; source code")
      (original-url "https://code.call-cc.org/releases/{scheme-version}/{name}")
      (scheme-id "chicken")
      (scheme-version "4.6.0"))

(file (name "{scheme-id}-{scheme-version}.tar.gz")
      (title "CHICKEN")
      (note "Scheme implementation; source code")
      (original-url "https://code.call-cc.org/releases/{scheme-version}/{name}")
      (scheme-id "chicken")
      (scheme-version "4.7.0"))

(file (name "{scheme-id}-{scheme-version}.tar.gz")
      (title "CHICKEN")
      (note "Scheme implementation; source code")
      (original-url "https://code.call-cc.org/releases/{scheme-version}/{name}")
      (scheme-id "chicken")
      (scheme-version "4.8.0"))

(file (name "{scheme-id}-{scheme-version}.tar.gz")
      (title "CHICKEN")
      (note "Scheme implementation; source code")
      (original-url "https://code.call-cc.org/releases/{scheme-version}/{name}")
      (scheme-id "chicken")
      (scheme-version "4.9.0"))

(file (name "{scheme-id}-{scheme-version}.tar.gz")
      (title "CHICKEN")
      (note "Scheme implementation; source code")
      (original-url "https://code.call-cc.org/releases/{scheme-version}/{name}")
      (scheme-id "chicken")
      (scheme-version "5.0.0"))

(file (name "{scheme-id}-{scheme-version}.tar.gz")
      (title "CHICKEN")
      (note "Scheme implementation; source code")
      (original-url "https://code.call-cc.org/releases/{scheme-version}/{name}")
      (scheme-id "chicken")
      (scheme-version "5.1.0"))

(file (name "{scheme-id}-{scheme-version}.tar.gz")
      (title "CHICKEN")
      (note "Scheme implementation; source code")
      (original-url "https://code.call-cc.org/releases/{scheme-version}/{name}")
      (scheme-id "chicken")
      (scheme-version "5.2.0"))

(file (name "csv{scheme-version}.tar.gz")
      (title "Chez Scheme")
      (note "Scheme implementation; source code")
      (original-url "https://github.com/cisco/ChezScheme/releases/download/v{scheme-version}/{name}")
      (scheme-id "chezscheme")
      (scheme-version "9.5"))

(file (name "csv{scheme-version}.tar.gz")
      (title "Chez Scheme")
      (note "Scheme implementation; source code")
      (original-url "https://github.com/cisco/ChezScheme/releases/download/v{scheme-version}/{name}")
      (scheme-id "chezscheme")
      (scheme-version "9.5.2"))

(file (name "csv{scheme-version}.tar.gz")
      (title "Chez Scheme")
      (note "Scheme implementation; source code")
      (original-url "https://github.com/cisco/ChezScheme/releases/download/v{scheme-version}/{name}")
      (scheme-id "chezscheme")
      (scheme-version "9.5.4"))

(file (name "{scheme-id}-{scheme-version}.tar.gz")
      (title "Elk")
      (note "Scheme implementation; source code")
      (original-url "ftp://ftp.cs.indiana.edu/pub/scheme-repository/imp/{name}")
      (scheme-id "elk")
      (scheme-version "3.0"))

(file (name "{scheme-id}-{scheme-version}.tar.gz")
      (title "Elk")
      (note "Scheme implementation; source code")
      (original-url "http://sam.zoy.org/elk/{name}")
      (scheme-id "elk")
      (scheme-version "3.99.8"))

(file (name "escm-{version}.tar.gz")
      (title "escm")
      (note "Embedded Scheme processor; source code")
      (original-url "http://practical-scheme.net/vault/escm-{version}.tar.gz")
      (version "1.1"))

(file (name "{scheme-id}-v{version-major}_{version-minor}_{version-patch}.tgz")
      (title "Gambit")
      (note "Scheme implementation; source code")
      (original-url "https://www.iro.umontreal.ca/~{scheme-id}/download/{scheme-id}/v{version-major}.{version-minor}/source/{name}")
      (scheme-id "gambit")
      (scheme-version "{version-major}.{version-minor}.{version-patch}")
      (version-major 4)
      (version-minor 8)
      (version-patch 0))

(file (name "{scheme-id}-v{version-major}_{version-minor}_{version-patch}.tgz")
      (title "Gambit")
      (note "Scheme implementation; source code")
      (original-url "https://www.iro.umontreal.ca/~{scheme-id}/download/{scheme-id}/v{version-major}.{version-minor}/source/{name}")
      (scheme-id "gambit")
      (scheme-version "{version-major}.{version-minor}.{version-patch}")
      (version-major 4)
      (version-minor 8)
      (version-patch 1))

(file (name "{scheme-id}-v{version-major}_{version-minor}_{version-patch}.tgz")
      (title "Gambit")
      (note "Scheme implementation; source code")
      (original-url "https://www.iro.umontreal.ca/~{scheme-id}/download/{scheme-id}/v{version-major}.{version-minor}/source/{name}")
      (scheme-id "gambit")
      (scheme-version "{version-major}.{version-minor}.{version-patch}")
      (version-major 4)
      (version-minor 8)
      (version-patch 2))

(file (name "{scheme-id}-v{version-major}_{version-minor}_{version-patch}.tgz")
      (title "Gambit")
      (note "Scheme implementation; source code")
      (original-url "https://www.iro.umontreal.ca/~{scheme-id}/download/{scheme-id}/v{version-major}.{version-minor}/source/{name}")
      (scheme-id "gambit")
      (scheme-version "{version-major}.{version-minor}.{version-patch}")
      (version-major 4)
      (version-minor 8)
      (version-patch 3))

(file (name "{scheme-id}-v{version-major}_{version-minor}_{version-patch}.tgz")
      (title "Gambit")
      (note "Scheme implementation; source code")
      (original-url "https://www.iro.umontreal.ca/~{scheme-id}/download/{scheme-id}/v{version-major}.{version-minor}/source/{name}")
      (scheme-id "gambit")
      (scheme-version "{version-major}.{version-minor}.{version-patch}")
      (version-major 4)
      (version-minor 8)
      (version-patch 4))

(file (name "{scheme-id}-v{version-major}_{version-minor}_{version-patch}.tgz")
      (title "Gambit")
      (note "Scheme implementation; source code")
      (original-url "https://www.iro.umontreal.ca/~{scheme-id}/download/{scheme-id}/v{version-major}.{version-minor}/source/{name}")
      (scheme-id "gambit")
      (scheme-version "{version-major}.{version-minor}.{version-patch}")
      (version-major 4)
      (version-minor 8)
      (version-patch 5))

(file (name "{scheme-id}-v{version-major}_{version-minor}_{version-patch}.tgz")
      (title "Gambit")
      (note "Scheme implementation; source code")
      (original-url "https://www.iro.umontreal.ca/~{scheme-id}/download/{scheme-id}/v{version-major}.{version-minor}/source/{name}")
      (scheme-id "gambit")
      (scheme-version "{version-major}.{version-minor}.{version-patch}")
      (version-major 4)
      (version-minor 8)
      (version-patch 6))

(file (name "{scheme-id}-v{version-major}_{version-minor}_{version-patch}.tgz")
      (title "Gambit")
      (note "Scheme implementation; source code")
      (original-url "https://www.iro.umontreal.ca/~{scheme-id}/download/{scheme-id}/v{version-major}.{version-minor}/source/{name}")
      (scheme-id "gambit")
      (scheme-version "{version-major}.{version-minor}.{version-patch}")
      (version-major 4)
      (version-minor 8)
      (version-patch 7))

(file (name "{scheme-id}-v{version-major}_{version-minor}_{version-patch}.tgz")
      (title "Gambit")
      (note "Scheme implementation; source code")
      (original-url "https://www.iro.umontreal.ca/~{scheme-id}/download/{scheme-id}/v{version-major}.{version-minor}/source/{name}")
      (scheme-id "gambit")
      (scheme-version "{version-major}.{version-minor}.{version-patch}")
      (version-major 4)
      (version-minor 8)
      (version-patch 8))

(file (name "{scheme-id}-v{version-major}_{version-minor}_{version-patch}.tgz")
      (title "Gambit")
      (note "Scheme implementation; source code")
      (original-url "https://www.iro.umontreal.ca/~{scheme-id}/download/{scheme-id}/v{version-major}.{version-minor}/source/{name}")
      (scheme-id "gambit")
      (scheme-version "{version-major}.{version-minor}.{version-patch}")
      (version-major 4)
      (version-minor 8)
      (version-patch 9))

(file (name "{scheme-id}-v{version-major}_{version-minor}_{version-patch}.tgz")
      (title "Gambit")
      (note "Scheme implementation; source code")
      (original-url "https://www.iro.umontreal.ca/~{scheme-id}/download/{scheme-id}/v{version-major}.{version-minor}/source/{name}")
      (scheme-id "gambit")
      (scheme-version "{version-major}.{version-minor}.{version-patch}")
      (version-major 4)
      (version-minor 9)
      (version-patch 0))

(file (name "{scheme-id}-v{version-major}_{version-minor}_{version-patch}.tgz")
      (title "Gambit")
      (note "Scheme implementation; source code")
      (original-url "https://www.iro.umontreal.ca/~{scheme-id}/download/{scheme-id}/v{version-major}.{version-minor}/source/{name}")
      (scheme-id "gambit")
      (scheme-version "{version-major}.{version-minor}.{version-patch}")
      (version-major 4)
      (version-minor 9)
      (version-patch 1))

(file (name "{scheme-id}-v{version-major}_{version-minor}_{version-patch}.tgz")
      (title "Gambit")
      (note "Scheme implementation; source code")
      (original-url "https://www.iro.umontreal.ca/~{scheme-id}/download/{scheme-id}/v{version-major}.{version-minor}/source/{name}")
      (scheme-id "gambit")
      (scheme-version "{version-major}.{version-minor}.{version-patch}")
      (version-major 4)
      (version-minor 9)
      (version-patch 2))

(file (name "{scheme-id}-v{version-major}_{version-minor}_{version-patch}.tgz")
      (title "Gambit")
      (note "Scheme implementation; source code")
      (original-url "https://www.iro.umontreal.ca/~{scheme-id}/download/{scheme-id}/v{version-major}.{version-minor}/source/{name}")
      (scheme-id "gambit")
      (scheme-version "{version-major}.{version-minor}.{version-patch}")
      (version-major 4)
      (version-minor 9)
      (version-patch 3))

(file (name "Gauche-{scheme-version}.tgz")
      (title "Gauche")
      (note "Scheme implementation; source code")
      (original-url "https://github.com/shirok/Gauche/releases/download/release{version-major}_{version-minor}_{version-patch}/{name}")
      (scheme-id "gauche")
      (scheme-version "{version-major}.{version-minor}.{version-patch}")
      (version-major 0)
      (version-minor 9)
      (version-patch 10))

(file (name "Gauche-{scheme-version}.tgz")
      (title "Gauche")
      (note "Scheme implementation; source code")
      (original-url "https://github.com/shirok/Gauche/releases/download/release{version-major}_{version-minor}_{version-patch}/{name}")
      (scheme-id "gauche")
      (scheme-version "{version-major}.{version-minor}.{version-patch}")
      (version-major 0)
      (version-minor 9)
      (version-patch 6))

(file (name "Gauche-{scheme-version}.tgz")
      (title "Gauche")
      (note "Scheme implementation; source code")
      (original-url "https://github.com/shirok/Gauche/releases/download/release{version-major}_{version-minor}_{version-patch}/{name}")
      (scheme-id "gauche")
      (scheme-version "{version-major}.{version-minor}.{version-patch}")
      (version-major 0)
      (version-minor 9)
      (version-patch 7))

(file (name "Gauche-{scheme-version}.tgz")
      (title "Gauche")
      (note "Scheme implementation; source code")
      (original-url "https://github.com/shirok/Gauche/releases/download/release{version-major}_{version-minor}_{version-patch}/{name}")
      (scheme-id "gauche")
      (scheme-version "{version-major}.{version-minor}.{version-patch}")
      (version-major 0)
      (version-minor 9)
      (version-patch 8))

(file (name "Gauche-{scheme-version}.tgz")
      (title "Gauche")
      (note "Scheme implementation; source code")
      (original-url "https://github.com/shirok/Gauche/releases/download/release{version-major}_{version-minor}_{version-patch}/{name}")
      (scheme-id "gauche")
      (scheme-version "{version-major}.{version-minor}.{version-patch}")
      (version-major 0)
      (version-minor 9)
      (version-patch 9))

(file (name "{scheme-id}-{scheme-version}.tar.gz")
      (title "Ikarus")
      (note "Scheme implementation; source code")
      (original-url "https://launchpad.net/ikarus/0.0/{scheme-version}/+download/{name}")
      (scheme-id "ikarus")
      (scheme-version "0.0.1"))

(file (name "{scheme-id}-{scheme-version}.tar.gz")
      (title "Ikarus")
      (note "Scheme implementation; source code")
      (original-url "https://launchpad.net/ikarus/0.0/{scheme-version}/+download/{name}")
      (scheme-id "ikarus")
      (scheme-version "0.0.2"))

(file (name "{scheme-id}-{scheme-version}.tar.gz")
      (title "Ikarus")
      (note "Scheme implementation; source code")
      (original-url "https://launchpad.net/ikarus/0.0/{scheme-version}/+download/{name}")
      (scheme-id "ikarus")
      (scheme-version "0.0.3"))

(file (name "{title}-{scheme-version}-{commit-hash}.zip")
      (title "IronScheme")
      (note "Scheme implementation; .NET/CLR binaries")
      (original-url "https://github.com/{title}/{title}/releases/download/{scheme-version}/{name}")
      (scheme-id "ironscheme")
      (scheme-version "1.0.240")
      (commit-hash "687cde5"))

(file (name "{scheme-id}-{scheme-version}-src.tar.gz")
      (title "Larceny")
      (note "Scheme implementation; source code")
      (original-url "http://larcenists.org/LarcenyReleases/{name}")
      (scheme-id "larceny")
      (scheme-version "0.97"))

(file (name "{scheme-id}-{scheme-version}-src.tar.gz")
      (title "Larceny")
      (note "Scheme implementation; source code")
      (original-url "http://larcenists.org/LarcenyReleases/{name}")
      (scheme-id "larceny")
      (scheme-version "1.3"))

(file (name "{scheme-id}-{scheme-version}.tar.gz")
      (title "libscheme")
      (note "Scheme implementation; source code")
      (original-url "ftp://ftp.cs.indiana.edu/pub/scheme-repository/imp/{name}")
      (scheme-id "libscheme")
      (scheme-version "0.5"))

(file (name "{scheme-id}-{scheme-version}.tar.gz")
      (title "Loko")
      (note "Scheme implementation; source code")
      (original-url "https://scheme.fail/releases/{name}")
      (scheme-id "loko")
      (scheme-version "0.1.0"))

(file (name "{scheme-id}-{scheme-version}.tar.gz")
      (title "Loko")
      (note "Scheme implementation; source code")
      (original-url "https://scheme.fail/releases/{name}")
      (scheme-id "loko")
      (scheme-version "0.2.0"))

(file (name "{scheme-id}-{scheme-version}.tar.gz")
      (title "Loko")
      (note "Scheme implementation; source code")
      (original-url "https://scheme.fail/releases/{name}")
      (scheme-id "loko")
      (scheme-version "0.2.1"))

(file (name "{scheme-id}-{scheme-version}.tar.gz")
      (title "Loko")
      (note "Scheme implementation; source code")
      (original-url "https://scheme.fail/releases/{name}")
      (scheme-id "loko")
      (scheme-version "0.3.0"))

(file (name "{scheme-id}-{scheme-version}.tar.gz")
      (title "Loko")
      (note "Scheme implementation; source code")
      (original-url "https://scheme.fail/releases/{name}")
      (scheme-id "loko")
      (scheme-version "0.3.1"))

(file (name "{scheme-id}-{scheme-version}.tar.gz")
      (title "Loko")
      (note "Scheme implementation; source code")
      (original-url "https://scheme.fail/releases/{name}")
      (scheme-id "loko")
      (scheme-version "0.3.2"))

(file (name "{scheme-id}-{scheme-version}.tar.gz")
      (title "Loko")
      (note "Scheme implementation; source code")
      (original-url "https://scheme.fail/releases/{name}")
      (scheme-id "loko")
      (scheme-version "0.3.3"))

(file (name "{scheme-id}-{scheme-version}.tar.gz")
      (title "Loko")
      (note "Scheme implementation; source code")
      (original-url "https://scheme.fail/releases/{name}")
      (scheme-id "loko")
      (scheme-version "0.3.4"))

(file (name "{scheme-id}-{scheme-version}.tar.gz")
      (title "Loko")
      (note "Scheme implementation; source code")
      (original-url "https://scheme.fail/releases/{name}")
      (scheme-id "loko")
      (scheme-version "0.4.0"))

(file (name "{scheme-id}-{scheme-version}.tar.gz")
      (title "Loko")
      (note "Scheme implementation; source code")
      (original-url "https://scheme.fail/releases/{name}")
      (scheme-id "loko")
      (scheme-version "0.4.1"))

(file (name "{scheme-id}-{scheme-version}.tar.gz")
      (title "Loko")
      (note "Scheme implementation; source code")
      (original-url "https://scheme.fail/releases/{name}")
      (scheme-id "loko")
      (scheme-version "0.4.2"))

(file (name "{scheme-id}-{scheme-version}.tar.gz")
      (title "Loko")
      (note "Scheme implementation; source code")
      (original-url "https://scheme.fail/releases/{name}")
      (scheme-id "loko")
      (scheme-version "0.4.3"))

(file (name "{scheme-id}-{scheme-version}.tar.gz")
      (title "Loko")
      (note "Scheme implementation; source code")
      (original-url "https://scheme.fail/releases/{name}")
      (scheme-id "loko")
      (scheme-version "0.4.4"))

(file (name "{scheme-id}-{scheme-version}.tar.gz")
      (title "Loko")
      (note "Scheme implementation; source code")
      (original-url "https://scheme.fail/releases/{name}")
      (scheme-id "loko")
      (scheme-version "0.5.0"))

(file (name "{scheme-id}-{scheme-version}.tar.gz")
      (title "Loko")
      (note "Scheme implementation; source code")
      (original-url "https://scheme.fail/releases/{name}")
      (scheme-id "loko")
      (scheme-version "0.6.0"))

(file (name "{scheme-id}-{scheme-version}.tar.gz")
      (title "Loko")
      (note "Scheme implementation; source code")
      (original-url "https://scheme.fail/releases/{name}")
      (scheme-id "loko")
      (scheme-version "0.7.0"))

(file (name "{scheme-id}-{scheme-version}.tar.gz")
      (title "Loko")
      (note "Scheme implementation; source code")
      (original-url "https://scheme.fail/releases/{name}")
      (scheme-id "loko")
      (scheme-version "0.8.0"))

(file (name "{scheme-id}-{scheme-version}.tar.gz")
      (title "Loko")
      (note "Scheme implementation; source code")
      (original-url "https://scheme.fail/releases/{name}")
      (scheme-id "loko")
      (scheme-version "0.9.0"))

(file (name "{scheme-id}-{scheme-version}.tar.gz")
      (title "Mosh")
      (note "Scheme implementation; source code")
      (original-url "https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/mosh-scheme/{name}")
      (scheme-id "mosh")
      (scheme-version "0.0.5")
      (approximate-release-date "2008-07-18"))

(file (name "{scheme-id}-{scheme-version}.tar.gz")
      (title "Mosh")
      (note "Scheme implementation; source code")
      (original-url "https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/mosh-scheme/{name}")
      (scheme-id "mosh")
      (scheme-version "0.0.6")
      (approximate-release-date "2008-08-29"))

(file (name "{scheme-id}-{scheme-version}.tar.gz")
      (title "Mosh")
      (note "Scheme implementation; source code")
      (original-url "https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/mosh-scheme/{name}")
      (scheme-id "mosh")
      (scheme-version "0.0.7")
      (approximate-release-date "2008-10-31"))

(file (name "{scheme-id}-{scheme-version}.tar.gz")
      (title "Mosh")
      (note "Scheme implementation; source code")
      (original-url "https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/mosh-scheme/{name}")
      (scheme-id "mosh")
      (scheme-version "0.1.0")
      (approximate-release-date "2009-05-03"))

(file (name "{scheme-id}-{scheme-version}-setup-win32.exe")
      (title "Mosh")
      (note "Scheme implementation; Windows installer; original filename mosh-0.0.1-setup-win32.exe")
      (original-url "https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/mosh-scheme/{name}")
      (scheme-id "mosh")
      (scheme-version "0.1.0")
      (approximate-release-date "2009-05-03"))

(file (name "{scheme-id}-{scheme-version}.tar.gz")
      (title "Mosh")
      (note "Scheme implementation; source code")
      (original-url "https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/mosh-scheme/{name}")
      (scheme-id "mosh")
      (scheme-version "0.1.1")
      (approximate-release-date "2009-05-07"))

(file (name "{scheme-id}-{scheme-version}.tar.gz")
      (title "Mosh")
      (note "Scheme implementation; source code")
      (original-url "https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/mosh-scheme/{name}")
      (scheme-id "mosh")
      (scheme-version "0.1.2")
      (approximate-release-date "2009-05-13"))

(file (name "{scheme-id}-{scheme-version}-setup-win32.exe")
      (title "Mosh")
      (note "Scheme implementation; Windows installer")
      (original-url "https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/mosh-scheme/{name}")
      (scheme-id "mosh")
      (scheme-version "0.1.2")
      (approximate-release-date "2009-05-13"))

(file (name "{scheme-id}-{scheme-version}.tar.gz")
      (title "Mosh")
      (note "Scheme implementation; source code")
      (original-url "https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/mosh-scheme/{name}")
      (scheme-id "mosh")
      (scheme-version "0.2.0")
      (approximate-release-date "2009-08-07"))

(file (name "{scheme-id}-{scheme-version}-setup-win32.exe")
      (title "Mosh")
      (note "Scheme implementation; Windows installer")
      (original-url "https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/mosh-scheme/{name}")
      (scheme-id "mosh")
      (scheme-version "0.2.0")
      (approximate-release-date "2009-08-07"))

(file (name "{scheme-id}-{scheme-version}-setup-win32.exe")
      (title "Mosh")
      (note "Scheme implementation; Windows installer")
      (original-url "https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/mosh-scheme/{name}")
      (scheme-id "mosh")
      (scheme-version "0.2.1")
      (approximate-release-date "2009-08-13"))

(file (name "{scheme-id}-{scheme-version}.tar.gz")
      (title "Mosh")
      (note "Scheme implementation; source code")
      (original-url "https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/mosh-scheme/{name}")
      (scheme-id "mosh")
      (scheme-version "0.2.2")
      (approximate-release-date "2010-02-09"))

(file (name "{scheme-id}-{scheme-version}.tar.gz")
      (title "Mosh")
      (note "Scheme implementation; source code")
      (original-url "https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/mosh-scheme/{name}")
      (scheme-id "mosh")
      (scheme-version "0.2.3")
      (approximate-release-date "2010-02-28"))

(file (name "{scheme-id}-{scheme-version}.tar.gz")
      (title "Mosh")
      (note "Scheme implementation; source code")
      (original-url "https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/mosh-scheme/{name}")
      (scheme-id "mosh")
      (scheme-version "0.2.4")
      (approximate-release-date "2010-04-15"))

(file (name "{scheme-id}-{scheme-version}-setup-win32.exe")
      (title "Mosh")
      (note "Scheme implementation; Windows installer")
      (original-url "https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/mosh-scheme/{name}")
      (scheme-id "mosh")
      (scheme-version "0.2.4")
      (approximate-release-date "2010-04-16"))

(file (name "{scheme-id}-{scheme-version}-1.tar.gz")
      (title "Mosh")
      (note "Scheme implementation; source code")
      (original-url "https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/mosh-scheme/{name}")
      (scheme-id "mosh")
      (scheme-version "0.2.5")
      (approximate-release-date "2010-05-16"))

(file (name "{scheme-id}-{scheme-version}-setup-win32.exe")
      (title "Mosh")
      (note "Scheme implementation; Windows installer; psyntax-mosh")
      (original-url "https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/mosh-scheme/{name}")
      (scheme-id "mosh")
      (scheme-version "0.2.5")
      (approximate-release-date "2010-05-16"))

(file (name "{scheme-id}-{scheme-version}.tar.gz")
      (title "Mosh")
      (note "Scheme implementation; source code")
      (original-url "https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/mosh-scheme/{name}")
      (scheme-id "mosh")
      (scheme-version "0.2.6")
      (approximate-release-date "2010-11-06"))

(file (name "{scheme-id}-{scheme-version}.tar.gz")
      (title "Mosh")
      (note "Scheme implementation; source code; for Homebrew")
      (original-url "https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/mosh-scheme/{name}")
      (scheme-id "mosh")
      (scheme-version "0.2.6p")
      (approximate-release-date "2010-11-06"))

(file (name "{scheme-id}-{scheme-version}.tar.gz")
      (title "Mosh")
      (note "Scheme implementation; source code")
      (original-url "https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/mosh-scheme/{name}")
      (scheme-id "mosh")
      (scheme-version "0.2.7")
      (approximate-release-date "2011-06-17"))

(file (name "oscheme-19950317.tar.gz")
      (title "Oscheme (Objective Scheme)")
      (note "Scheme implementation; source code; no version number in archive")
      (original-url "ftp://ftp.cs.indiana.edu/pub/scheme-repository/imp/oscheme.tar.gz"))

(file (name "owl-v{scheme-version}.tar.gz")
      (title "Owl Lisp")
      (note "Scheme implementation; source code")
      (original-url "https://gitlab.com/owl-lisp/owl/-/archive/v{scheme-version}/{name}")
      (scheme-version "0.1.16"))

(file (name "owl-v{scheme-version}.tar.gz")
      (title "Owl Lisp")
      (note "Scheme implementation; source code")
      (original-url "https://gitlab.com/owl-lisp/owl/-/archive/v{scheme-version}/{name}")
      (scheme-version "0.1.17"))

(file (name "owl-v{scheme-version}.tar.gz")
      (title "Owl Lisp")
      (note "Scheme implementation; source code")
      (original-url "https://gitlab.com/owl-lisp/owl/-/archive/v{scheme-version}/{name}")
      (scheme-version "0.1.18"))

(file (name "owl-v{scheme-version}.tar.gz")
      (title "Owl Lisp")
      (note "Scheme implementation; source code")
      (original-url "https://gitlab.com/owl-lisp/owl/-/archive/v{scheme-version}/{name}")
      (scheme-version "0.1.19"))

(file (name "owl-v{scheme-version}.tar.gz")
      (title "Owl Lisp")
      (note "Scheme implementation; source code")
      (original-url "https://gitlab.com/owl-lisp/owl/-/archive/v{scheme-version}/{name}")
      (scheme-version "0.1.20"))

(file (name "owl-v{scheme-version}.tar.gz")
      (title "Owl Lisp")
      (note "Scheme implementation; source code")
      (original-url "https://gitlab.com/owl-lisp/owl/-/archive/v{scheme-version}/{name}")
      (scheme-version "0.1.21"))

(file (name "owl-v{scheme-version}.tar.gz")
      (title "Owl Lisp")
      (note "Scheme implementation; source code")
      (original-url "https://gitlab.com/owl-lisp/owl/-/archive/v{scheme-version}/{name}")
      (scheme-version "0.2"))

(file (name "psyntax-r6rs-{version}.tgz")
      (title "psyntax")
      (note "portable R6RS library expander; source code")
      (original-url "https://www.scheme.com/syntax-case/r6rs-libraries/{name}")
      (version "rev1"))

(file (name "psyntax-r6rs-{version}.tgz")
      (title "psyntax")
      (note "portable R6RS library expander; source code")
      (original-url "https://www.scheme.com/syntax-case/r6rs-libraries/{name}")
      (version "rev4"))

(file (name "{title}-{version}.tar.Z")
      (title "QobiScheme")
      (note "Scheme libraries; source code")
      (original-url "ftp://ftp.ecn.purdue.edu/qobi/{name}")
      (version "1.47"))

(file (name "r2rs-nbs.pdf")
      (title "The Revised Revised Report on Scheme or An UnCommon Lisp (AI Memo No. 848)")
      (note "also known as R^2RS; scanned OCR PDF from National Bureau of Standards")
      (original-url "https://apps.dtic.mil/sti/pdfs/ADA159423.pdf")
      (rnrs 2))

(file (name "rabbit.lsp")
      (title "Rabbit")
      (note "source code from the paper Rabbit: a compiler for Scheme")
      (original-url "http://www.cs.cmu.edu/afs/cs/project/ai-repository/ai/lang/scheme/impl/rabbit/{name}"))

(file (name "rs-{scheme-version}.tar.gz")
      (title "RScheme")
      (note "Scheme implementation; source code")
      (manual-original-url "https://web.archive.org/web/20160804005509/http://www.rscheme.org/rs/b/0.7.3.4/7/{name}")
      (scheme-id "rscheme")
      (scheme-version "0.7.3.4-b7"))

(file (name "s9core-{scheme-version}.tgz")
      (title "Scheme 9 from Empty Space, Reimagined (core)")
      (note "C library for interpreter building; source code")
      (original-url "http://t3x.org/{scheme-id}/{name}")
      (scheme-id "s9fes")
      (scheme-version "20181205"))

(file (name "{scheme-id}-{year}.tgz")
      (title "Scheme 9 from Empty Space")
      (note "Scheme implementation; source code from 1st edition of book; includes 2009 errata fixes")
      (original-url "https://t3x.org/files/{name}")
      (scheme-id "s9fes")
      (year "2007"))

(file (name "{scheme-id}-{year}.tgz")
      (title "Scheme 9 from Empty Space")
      (note "Scheme implementation; source code from 3rd edition of book")
      (original-url "https://t3x.org/files/{name}")
      (scheme-id "s9fes")
      (year "2014"))

(file (name "{scheme-id}-{year}.tgz")
      (title "Scheme 9 from Empty Space")
      (note "Scheme implementation; source code")
      (original-url "https://t3x.org/files/{name}")
      (scheme-id "s9fes")
      (year "2018"))

(file (name "{scheme-id}-{scheme-version}.tgz")
      (title "Scheme 9 from Empty Space, Reimagined")
      (note "Scheme implementation; source code")
      (original-url "http://t3x.org/{scheme-id}/{name}")
      (scheme-id "s9fes")
      (scheme-version "20181205"))

(file (name "{scheme-id}-{scheme-version}.tar.gz")
      (title "Sagittarius")
      (note "Scheme implementation; source code")
      (original-url "https://bitbucket.org/ktakashi/sagittarius-scheme/downloads/{name}")
      (scheme-id "sagittarius")
      (scheme-version "0.9.7"))

(file (name "{scheme-id}-{scheme-version}.tgz")
      (title "Scheme 48")
      (note "Scheme implementation; source code")
      (original-url "https://www.s48.org/{scheme-version}/{name}")
      (scheme-id "scheme48")
      (scheme-version "0.52"))

(file (name "{scheme-id}-{scheme-version}.tgz")
      (title "Scheme 48")
      (note "Scheme implementation; source code")
      (original-url "https://www.s48.org/{scheme-version}/{name}")
      (scheme-id "scheme48")
      (scheme-version "0.53"))

(file (name "{scheme-id}-{scheme-version}.tgz")
      (title "Scheme 48")
      (note "Scheme implementation; source code")
      (original-url "https://www.s48.org/{scheme-version}/{name}")
      (scheme-id "scheme48")
      (scheme-version "0.54"))

(file (name "{scheme-id}-{scheme-version}.tgz")
      (title "Scheme 48")
      (note "Scheme implementation; source code")
      (original-url "https://www.s48.org/{scheme-version}/{name}")
      (scheme-id "scheme48")
      (scheme-version "0.55"))

(file (name "{scheme-id}-{scheme-version}.tgz")
      (title "Scheme 48")
      (note "Scheme implementation; source code")
      (original-url "https://www.s48.org/{scheme-version}/{name}")
      (scheme-id "scheme48")
      (scheme-version "0.56"))

(file (name "{scheme-id}-{scheme-version}.tgz")
      (title "Scheme 48")
      (note "Scheme implementation; source code")
      (original-url "https://www.s48.org/{scheme-version}/{name}")
      (scheme-id "scheme48")
      (scheme-version "0.57"))

(file (name "{scheme-id}-{scheme-version}.tgz")
      (title "Scheme 48")
      (note "Scheme implementation; source code; does not build")
      (original-url "https://www.s48.org/{scheme-version}/{name}")
      (scheme-id "scheme48")
      (scheme-version "0.58"))

(file (name "{scheme-id}-{scheme-version}.tgz")
      (title "Scheme 48")
      (note "Scheme implementation; source code")
      (original-url "https://www.s48.org/{scheme-version}/{name}")
      (scheme-id "scheme48")
      (scheme-version "1.1"))

(file (name "{scheme-id}-{scheme-version}.tgz")
      (title "Scheme 48")
      (note "Scheme implementation; source code")
      (original-url "https://www.s48.org/{scheme-version}/{name}")
      (scheme-id "scheme48")
      (scheme-version "1.2"))

(file (name "{scheme-id}-{scheme-version}.tgz")
      (title "Scheme 48")
      (note "Scheme implementation; source code")
      (original-url "https://www.s48.org/{scheme-version}/{name}")
      (scheme-id "scheme48")
      (scheme-version "1.3"))

(file (name "{scheme-id}-{scheme-version}.tgz")
      (title "Scheme 48")
      (note "Scheme implementation; source code")
      (original-url "https://www.s48.org/{scheme-version}/{name}")
      (scheme-id "scheme48")
      (scheme-version "1.4"))

(file (name "{scheme-id}-{scheme-version}.tgz")
      (title "Scheme 48")
      (note "Scheme implementation; source code")
      (original-url "https://www.s48.org/{scheme-version}/{name}")
      (scheme-id "scheme48")
      (scheme-version "1.5"))

(file (name "{scheme-id}-{scheme-version}.tgz")
      (title "Scheme 48")
      (note "Scheme implementation; source code")
      (original-url "https://www.s48.org/{scheme-version}/{name}")
      (scheme-id "scheme48")
      (scheme-version "1.6"))

(file (name "{scheme-id}-{scheme-version}.tgz")
      (title "Scheme 48")
      (note "Scheme implementation; source code")
      (original-url "https://www.s48.org/{scheme-version}/{name}")
      (scheme-id "scheme48")
      (scheme-version "1.7"))

(file (name "{scheme-id}-{scheme-version}.tgz")
      (title "Scheme 48")
      (note "Scheme implementation; source code")
      (original-url "https://www.s48.org/{scheme-version}/{name}")
      (scheme-id "scheme48")
      (scheme-version "1.8"))

(file (name "{scheme-id}-{scheme-version}.tgz")
      (title "Scheme 48")
      (note "Scheme implementation; source code")
      (original-url "https://www.s48.org/{scheme-version}/{name}")
      (scheme-id "scheme48")
      (scheme-version "1.9"))

(file (name "{scheme-id}-{scheme-version}.tgz")
      (title "Scheme 48")
      (note "Scheme implementation; source code")
      (original-url "https://www.s48.org/{scheme-version}/{name}")
      (scheme-id "scheme48")
      (scheme-version "1.9.1"))

(file (name "{scheme-id}-{scheme-version}.tgz")
      (title "Scheme 48")
      (note "Scheme implementation; source code")
      (original-url "https://www.s48.org/{scheme-version}/{name}")
      (scheme-id "scheme48")
      (scheme-version "1.9.2"))

(file (name "{scheme-id}-{scheme-version}.zip")
      (title "SCM")
      (note "Scheme implementation; source code")
      (original-url "http://groups.csail.mit.edu/mac/ftpdir/{scheme-id}/{name}")
      (scheme-id "scm")
      (scheme-version "5f1"))

(file (name "{scheme-id}-{scheme-version}.zip")
      (title "SCM")
      (note "Scheme implementation; source code")
      (original-url "http://groups.csail.mit.edu/mac/ftpdir/{scheme-id}/{name}")
      (scheme-id "scm")
      (scheme-version "5f2"))

(file (name "{scheme-id}-{scheme-version}.zip")
      (title "SCM")
      (note "Scheme implementation; source code")
      (original-url "http://groups.csail.mit.edu/mac/ftpdir/{scheme-id}/{name}")
      (scheme-id "scm")
      (scheme-version "5f3"))

(file (name "{scheme-id}-{scheme-version}.tar.gz")
      (title "scsh Scheme shell")
      (note "source code")
      (original-url "ftp://ftp.cs.indiana.edu/pub/scheme-repository/imp/{name}")
      (scheme-id "scsh")
      (scheme-version "0.5.0"))

(file (name "{scheme-id}-{scheme-version}.tar.gz")
      (title "SIOD: Scheme in One Defun")
      (note "Scheme implementation; source code")
      (original-url "ftp://ftp.cs.indiana.edu/pub/scheme-repository/imp/{name}")
      (scheme-id "siod")
      (scheme-version "3.0"))

(file (name "{scheme-id}-{scheme-version}.tar.gz")
      (title "SIOD: Scheme in One Defun")
      (note "Scheme implementation; source code")
      (original-url "ftp://ftp.cs.indiana.edu/pub/scheme-repository/imp/{name}")
      (scheme-id "siod")
      (scheme-version "3.2"))

(file (name "slib-{version}.tar.gz")
      (title "SLIB")
      (note "Scheme library; source code")
      (original-url "http://groups.csail.mit.edu/mac/ftpdir/scm/{name}")
      (version "3b4"))

(file (name "slib-{version}.zip")
      (title "SLIB")
      (note "Scheme library; source code")
      (original-url "http://groups.csail.mit.edu/mac/ftpdir/scm/{name}")
      (version "3b4"))

(file (name "slib-{version}.tar.gz")
      (title "SLIB")
      (note "Scheme library; source code")
      (original-url "http://groups.csail.mit.edu/mac/ftpdir/scm/{name}")
      (version "3b5"))

(file (name "slib-{version}.zip")
      (title "SLIB")
      (note "Scheme library; source code")
      (original-url "http://groups.csail.mit.edu/mac/ftpdir/scm/{name}")
      (version "3b5"))

(file (name "slib-{version}.tar.gz")
      (title "SLIB")
      (note "Scheme library; source code")
      (original-url "http://groups.csail.mit.edu/mac/ftpdir/scm/{name}")
      (version "3b6"))

(file (name "slib-{version}.zip")
      (title "SLIB")
      (note "Scheme library; source code")
      (original-url "http://groups.csail.mit.edu/mac/ftpdir/scm/{name}")
      (version "3b6"))

(file (name "{scheme-id}-{scheme-version}.tgz")
      (title "Stalin")
      (note "Scheme implementation; source code")
      (original-url "ftp://ftp.ecn.purdue.edu/qobi/{name}")
      (scheme-id "stalin")
      (scheme-version "0.11"))

(file (name "STk-{scheme-version}.tar.gz")
      (title "STk")
      (note "Scheme implementation; source code")
      (original-url "http://kaolin.unice.fr/STk/Distrib/{name}")
      (scheme-id "stk")
      (scheme-version "3.1.1"))

(file (name "STk-{scheme-version}.tar.gz")
      (title "STk")
      (note "Scheme implementation; source code")
      (original-url "http://kaolin.unice.fr/STk/Distrib/{name}")
      (scheme-id "stk")
      (scheme-version "3.99.0"))

(file (name "STk-{scheme-version}.tar.gz")
      (title "STk")
      (note "Scheme implementation; source code")
      (original-url "http://kaolin.unice.fr/STk/Distrib/{name}")
      (scheme-id "stk")
      (scheme-version "3.99.1"))

(file (name "STk-{scheme-version}.tar.gz")
      (title "STk")
      (note "Scheme implementation; source code")
      (original-url "http://kaolin.unice.fr/STk/Distrib/{name}")
      (scheme-id "stk")
      (scheme-version "3.99.2"))

(file (name "STk-{scheme-version}.tar.gz")
      (title "STk")
      (note "Scheme implementation; source code")
      (original-url "http://kaolin.unice.fr/STk/Distrib/{name}")
      (scheme-id "stk")
      (scheme-version "3.99.3"))

(file (name "STk-{scheme-version}.tar.gz")
      (title "STk")
      (note "Scheme implementation; source code")
      (original-url "http://kaolin.unice.fr/STk/Distrib/{name}")
      (scheme-id "stk")
      (scheme-version "3.99.4"))

(file (name "STk-{scheme-version}.tar.gz")
      (title "STk")
      (note "Scheme implementation; source code")
      (original-url "http://kaolin.unice.fr/STk/Distrib/{name}")
      (scheme-id "stk")
      (scheme-version "4.0.0"))

(file (name "STk-{scheme-version}.tar.gz")
      (title "STk")
      (note "Scheme implementation; source code")
      (original-url "http://kaolin.unice.fr/STk/Distrib/{name}")
      (scheme-id "stk")
      (scheme-version "4.0.1"))

(file (name "stklos-{scheme-version}.tar.gz")
      (title "STklos")
      (note "Scheme implementation; source code")
      (original-url "https://stklos.net/download/{name}")
      (scheme-id "stklos")
      (scheme-version "1.00")
      (release-date "2010-08-11"))

(file (name "stklos-{scheme-version}.tar.gz")
      (title "STklos")
      (note "Scheme implementation; source code")
      (original-url "https://stklos.net/download/{name}")
      (scheme-id "stklos")
      (scheme-version "1.01")
      (release-date "2010-12-30"))

(file (name "stklos-{scheme-version}.tar.gz")
      (title "STklos")
      (note "Scheme implementation; source code")
      (original-url "https://stklos.net/download/{name}")
      (scheme-id "stklos")
      (scheme-version "1.10")
      (release-date "2011-12-31"))

(file (name "stklos-{scheme-version}.tar.gz")
      (title "STklos")
      (note "Scheme implementation; source code")
      (original-url "https://stklos.net/download/{name}")
      (scheme-id "stklos")
      (scheme-version "1.20")
      (release-date "2018-06-04"))

(file (name "stklos-{scheme-version}.tar.gz")
      (title "STklos")
      (note "Scheme implementation; source code")
      (original-url "https://stklos.net/download/{name}")
      (scheme-id "stklos")
      (scheme-version "1.30")
      (release-date "2019-07-04"))

(file (name "stklos-{scheme-version}.tar.gz")
      (title "STklos")
      (note "Scheme implementation; source code")
      (original-url "https://stklos.net/download/{name}")
      (scheme-id "stklos")
      (scheme-version "1.31")
      (release-date "2019-07-13"))

(file (name "stklos-{scheme-version}.tar.gz")
      (title "STklos")
      (note "Scheme implementation; source code")
      (original-url "https://stklos.net/download/{name}")
      (scheme-id "stklos")
      (scheme-version "1.40")
      (release-date "2020-06-05"))

(file (name "stklos-{scheme-version}.tar.gz")
      (title "STklos")
      (note "Scheme implementation; source code")
      (original-url "https://stklos.net/download/{name}")
      (scheme-id "stklos")
      (scheme-version "1.50")
      (release-date "2020-08-17"))

(file (name "{scheme-id}-{scheme-version}.tar.gz")
      (title "TinyScheme")
      (note "Scheme implementation; source code")
      (original-url "https://sourceforge.net/projects/{scheme-id}/files/{scheme-id}/TinyScheme%20archive/{name}/download")
      (scheme-id "tinyscheme")
      (scheme-version "1.19"))

(file (name "{scheme-id}-{scheme-version}.tar.gz")
      (title "TinyScheme")
      (note "Scheme implementation; source code")
      (original-url "https://sourceforge.net/projects/{scheme-id}/files/{scheme-id}/TinyScheme%20archive/{name}/download")
      (scheme-id "tinyscheme")
      (scheme-version "1.20"))

(file (name "{scheme-id}-{scheme-version}.tar.gz")
      (title "TinyScheme")
      (note "Scheme implementation; source code")
      (original-url "https://sourceforge.net/projects/{scheme-id}/files/{scheme-id}/TinyScheme%20archive/{name}/download")
      (scheme-id "tinyscheme")
      (scheme-version "1.21"))

(file (name "{scheme-id}-{scheme-version}.tar.gz")
      (title "TinyScheme")
      (note "Scheme implementation; source code")
      (original-url "https://sourceforge.net/projects/{scheme-id}/files/{scheme-id}/TinyScheme%20archive/{name}/download")
      (scheme-id "tinyscheme")
      (scheme-version "1.22"))

(file (name "{scheme-id}-{scheme-version}.tar.gz")
      (title "TinyScheme")
      (note "Scheme implementation; source code")
      (original-url "https://sourceforge.net/projects/{scheme-id}/files/{scheme-id}/TinyScheme%20archive/{name}/download")
      (scheme-id "tinyscheme")
      (scheme-version "1.23"))

(file (name "{scheme-id}-{scheme-version}.tar.gz")
      (title "TinyScheme")
      (note "Scheme implementation; source code")
      (original-url "https://sourceforge.net/projects/{scheme-id}/files/{scheme-id}/TinyScheme%20archive/{name}/download")
      (scheme-id "tinyscheme")
      (scheme-version "1.24"))

(file (name "{scheme-id}-{scheme-version}.tar.gz")
      (title "TinyScheme")
      (note "Scheme implementation; source code")
      (original-url "https://sourceforge.net/projects/{scheme-id}/files/{scheme-id}/TinyScheme%20archive/{name}/download")
      (scheme-id "tinyscheme")
      (scheme-version "1.25"))

(file (name "{scheme-id}-{scheme-version}.tar.gz")
      (title "TinyScheme")
      (note "Scheme implementation; source code")
      (original-url "https://sourceforge.net/projects/{scheme-id}/files/{scheme-id}/TinyScheme%20archive/{name}/download")
      (scheme-id "tinyscheme")
      (scheme-version "1.27"))

(file (name "{scheme-id}-{scheme-version}.tar.gz")
      (title "TinyScheme")
      (note "Scheme implementation; source code")
      (original-url "https://sourceforge.net/projects/{scheme-id}/files/{scheme-id}/TinyScheme%20archive/{name}/download")
      (scheme-id "tinyscheme")
      (scheme-version "1.28"))

(file (name "{scheme-id}-{scheme-version}.tar.gz")
      (title "TinyScheme")
      (note "Scheme implementation; source code")
      (original-url "https://sourceforge.net/projects/{scheme-id}/files/{scheme-id}/TinyScheme%20archive/{name}/download")
      (scheme-id "tinyscheme")
      (scheme-version "1.29"))

(file (name "{scheme-id}-{scheme-version}.tar.gz")
      (title "TinyScheme")
      (note "Scheme implementation; source code")
      (original-url "https://sourceforge.net/projects/{scheme-id}/files/{scheme-id}/TinyScheme%20archive/{name}/download")
      (scheme-id "tinyscheme")
      (scheme-version "1.30"))

(file (name "{scheme-id}-{scheme-version}.tar.gz")
      (title "TinyScheme")
      (note "Scheme implementation; source code")
      (original-url "https://sourceforge.net/projects/{scheme-id}/files/{scheme-id}/TinyScheme%20archive/{name}/download")
      (scheme-id "tinyscheme")
      (scheme-version "1.31"))

(file (name "{scheme-id}-{scheme-version}.tar.gz")
      (title "TinyScheme")
      (note "Scheme implementation; source code")
      (original-url "https://sourceforge.net/projects/{scheme-id}/files/{scheme-id}/TinyScheme%20archive/{name}/download")
      (scheme-id "tinyscheme")
      (scheme-version "1.32"))

(file (name "{scheme-id}-{scheme-version}.tar.gz")
      (title "TinyScheme")
      (note "Scheme implementation; source code")
      (original-url "https://sourceforge.net/projects/{scheme-id}/files/{scheme-id}/TinyScheme%20archive/{name}/download")
      (scheme-id "tinyscheme")
      (scheme-version "1.33"))

(file (name "{scheme-id}-{scheme-version}.tar.gz")
      (title "TinyScheme")
      (note "Scheme implementation; source code")
      (original-url "https://sourceforge.net/projects/{scheme-id}/files/{scheme-id}/TinyScheme%20archive/{name}/download")
      (scheme-id "tinyscheme")
      (scheme-version "1.34"))

(file (name "{scheme-id}-{scheme-version}.tar.gz")
      (title "TinyScheme")
      (note "Scheme implementation; source code")
      (original-url "https://sourceforge.net/projects/{scheme-id}/files/{scheme-id}/{scheme-id}-{scheme-version}/{name}/download")
      (scheme-id "tinyscheme")
      (scheme-version "1.35"))

(file (name "{scheme-id}-{scheme-version}.zip")
      (title "TinyScheme")
      (note "Scheme implementation; source code")
      (original-url "https://sourceforge.net/projects/{scheme-id}/files/{scheme-id}/{scheme-id}-{scheme-version}/{name}/download")
      (scheme-id "tinyscheme")
      (scheme-version "1.36"))

(file (name "{scheme-id}-{scheme-version}.tar.gz")
      (title "TinyScheme")
      (note "Scheme implementation; source code")
      (manual-original-url "https://sourceforge.net/projects/{scheme-id}/files/{scheme-id}/{scheme-id}-{scheme-version}/{name}/download")
      (scheme-id "tinyscheme")
      (scheme-version "1.40"))

(file (name "{scheme-id}-{scheme-version}.tar.gz")
      (title "TinyScheme")
      (note "Scheme implementation; source code")
      (manual-original-url "https://sourceforge.net/projects/{scheme-id}/files/{scheme-id}/{scheme-id}-{scheme-version}/{name}/download")
      (scheme-id "tinyscheme")
      (scheme-version "1.41"))

(file (name "{scheme-id}-{scheme-version}.zip")
      (title "TinyScheme")
      (note "Scheme implementation; source code")
      (manual-original-url "https://sourceforge.net/projects/{scheme-id}/files/{scheme-id}/{scheme-id}-{scheme-version}/{name}/download")
      (scheme-id "tinyscheme")
      (scheme-version "1.41"))

(file (name "{scheme-id}-{scheme-version}.tar.gz")
      (title "TinyScheme")
      (note "Scheme implementation; source code")
      (manual-original-url "https://sourceforge.net/projects/{scheme-id}/files/{scheme-id}/{scheme-id}-{scheme-version}/{name}/download")
      (scheme-id "tinyscheme")
      (scheme-version "1.42"))

(file (name "{scheme-id}-{scheme-version}.zip")
      (title "TinyScheme")
      (note "Scheme implementation; source code")
      (manual-original-url "https://sourceforge.net/projects/{scheme-id}/files/{scheme-id}/{scheme-id}-{scheme-version}/{name}/download")
      (scheme-id "tinyscheme")
      (scheme-version "1.42"))

(file (name "{scheme-id}{scheme-version}.zip")
      (title "TinyScheme")
      (note "Scheme implementation; source code")
      (original-url "https://sourceforge.net/projects/{scheme-id}/files/{scheme-id}/{scheme-id}-{scheme-version}/{name}/download")
      (scheme-id "tinyscheme")
      (scheme-version "1.37"))

(file (name "{scheme-id}{scheme-version}.zip")
      (title "TinyScheme")
      (note "Scheme implementation; source code")
      (original-url "https://sourceforge.net/projects/{scheme-id}/files/{scheme-id}/{scheme-id}-{scheme-version}/{name}/download")
      (scheme-id "tinyscheme")
      (scheme-version "1.38"))

(file (name "{scheme-id}{scheme-version}.zip")
      (title "TinyScheme")
      (note "Scheme implementation; source code")
      (original-url "https://sourceforge.net/projects/{scheme-id}/files/{scheme-id}/{scheme-id}-{scheme-version}/{name}/download")
      (scheme-id "tinyscheme")
      (scheme-version "1.39"))

(file (name "vx-scheme-20080617-repo.git.tar.gz")
      (title "Vx-Scheme")
      (note "Scheme implementation; svn to git conversion from Lassi Kortela")
      (original-url "https://misc.lassi.io/2021/vx-scheme-20080617-repo.git.tar.gz"))

(file (name "vx-scheme-20080617-repo.svndump.gz")
      (title "Vx-Scheme")
      (note "Scheme implementation; final Subversion repository from Google Code")
      (original-url "https://storage.googleapis.com/google-code-archive-source/v2/code.google.com/vx-scheme/repo.svndump.gz"))

(file (name "{scheme-id}-{scheme-version}.tar.gz")
      (title "Ypsilon")
      (note "Scheme implementation; source code")
      (original-url "https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/{scheme-id}/{name}")
      (scheme-id "ypsilon")
      (scheme-version "0.9.6.update3"))
