(file (name "errata-corrected-r6rs-app.pdf")
      (title "Revised^6 Report on the Algorithmic Language Scheme -- Non-Normative Appendices")
      (note "unofficial errata-corrected version from Göran Weinholt")
      (original-url "https://weinholt.se/scheme/r6rs/r6rs-app.pdf")
      (rnrs 6))

(file (name "errata-corrected-r6rs-lib.pdf")
      (title "Revised^6 Report on the Algorithmic Language Scheme -- Standard Libraries")
      (note "unofficial errata-corrected version from Göran Weinholt")
      (original-url "https://weinholt.se/scheme/r6rs/r6rs-lib.pdf")
      (rnrs 6))

(file (name "errata-corrected-r6rs-rationale.pdf")
      (title "Revised^6 Report on the Algorithmic Language Scheme -- Rationale")
      (note "unofficial errata-corrected version from Göran Weinholt")
      (original-url "https://weinholt.se/scheme/r6rs/r6rs-rationale.pdf")
      (rnrs 6))

(file (name "errata-corrected-r6rs.pdf")
      (title "Revised^6 Report on the Algorithmic Language Scheme")
      (note "unofficial errata-corrected version from Göran Weinholt")
      (original-url "https://weinholt.se/scheme/r6rs/r6rs.pdf")
      (rnrs 6))

(file (name "errata-corrected-r7rs.pdf")
      (title "Revised^7 Report on the Algorithmic Language Scheme")
      (note "unofficial errata-corrected version from John Cowan")
      (original-url "https://raw.githubusercontent.com/johnwcowan/r7rs-spec/errata/rnrs/r7rs.pdf")
      (rnrs 7))

(file (name "gambit-v4_9_3.tgz")
      (title "Gambit Scheme")
      (note "source code")
      (original-url "https://www.iro.umontreal.ca/~gambit/download/gambit/v4.9/source/gambit-v4_9_3.tgz")
      (scheme-id "gambit")
      (scheme-release "4.9.3"))

(file (name "r5rs.pdf")
      (title "Revised^5 Report on the Algorithmic Language Scheme")
      (note "official standard; PDF by Brad Lucier")
      (original-url "https://schemers.org/Documents/Standards/R5RS/r5rs.pdf")
      (rnrs 5))

(file (name "r6rs-app.pdf")
      (title "Revised^6 Report on the Algorithmic Language Scheme -- Non-Normative Appendices")
      (note "official standard")
      (original-url "http://www.r6rs.org/final/r6rs-app.pdf")
      (rnrs 6))

(file (name "r6rs-lib.pdf")
      (title "Revised^6 Report on the Algorithmic Language Scheme -- Standard Libraries")
      (note "official standard")
      (original-url "http://www.r6rs.org/final/r6rs-lib.pdf")
      (rnrs 6))

(file (name "r6rs-rationale.pdf")
      (title "Revised^6 Report on the Algorithmic Language Scheme -- Rationale")
      (note "official standard")
      (original-url "http://www.r6rs.org/final/r6rs-rationale.pdf")
      (rnrs 6))

(file (name "r6rs.pdf")
      (title "Revised^6 Report on the Algorithmic Language Scheme")
      (note "official standard")
      (original-url "http://www.r6rs.org/final/r6rs.pdf")
      (rnrs 6))

(file (name "r7rs.pdf")
      (title "Revised^7 Report on the Algorithmic Language Scheme")
      (note "official standard")
      (original-url "https://raw.githubusercontent.com/johnwcowan/r7rs-spec/errata/rnrs/r7rs-official.pdf")
      (rnrs 7))

(file (name "s9core-20181205.tgz")
      (title "Scheme 9 from Empty Space")
      (original-url "http://t3x.org/s9fes/s9core-20181205.tgz")
      (scheme-id "s9fes")
      (scheme-release "20181205"))

(file (name "s9fes-20181205.tgz")
      (title "Scheme 9 from Empty Space")
      (original-url "http://t3x.org/s9fes/s9fes-20181205.tgz")
      (scheme-id "s9fes")
      (scheme-release "20181205"))

(file (name "sigscheme-0.9.1.tar.gz")
      (title "SigScheme")
      (note "source code")
      (original-url "https://github.com/uim/sigscheme/releases/download/0.9.1/sigscheme-0.9.1.tar.gz")
      (scheme-id "sigscheme")
      (scheme-release "0.9.1"))
